import {test,expect} from '@playwright/test';
test('tap loads just one video; end returns to poster without layout change',async({page})=>{const videos=[];page.on('request',r=>{if(r.url().endsWith('.mp4'))videos.push(r.url());});await page.goto('/');await expect(page.getByRole('heading',{level:1})).toBeVisible();expect(videos).toHaveLength(0);const rect=await page.locator('.page').boundingBox();await page.getByRole('button',{name:/再生/}).click();await expect(page.locator('video')).toBeVisible();await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime)).toBeGreaterThan(0);await page.screenshot({path:'test-results/reader-playing.png',fullPage:true});await expect(page.locator('video')).toHaveCount(0,{timeout:10000});await expect(page.getByRole('status')).toContainText('▶');expect(await page.locator('.page').boundingBox()).toEqual(rect);await page.getByRole('checkbox').check();await expect(page.getByRole('button',{name:/再生/})).toHaveCount(0);await page.getByText('テキストで読む',{exact:true}).click();await expect(page.getByText('静かな午後。',{exact:true})).toBeVisible();});
test('404 and play rejection preserve readable page and permit retry',async({page})=>{await page.route('**/*.mp4',r=>r.fulfill({status:404}));await page.goto('/');await page.getByRole('button',{name:/再生/}).click();await expect(page.getByRole('status')).toContainText('再試行');await expect(page.locator('video')).toHaveCount(0);await expect(page.locator('.page')).toBeVisible();await page.unroute('**/*.mp4');await page.evaluate(()=>{HTMLMediaElement.prototype.play=()=>Promise.reject(new Error('denied'));});await page.getByRole('button',{name:/再生/}).click();await expect(page.getByRole('status')).toContainText('再試行');});
test('reduced motion never fetches video; mobile layout',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.getByRole('checkbox')).toBeChecked();await expect(page.locator('video')).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);await page.screenshot({path:'test-results/reader-mobile.png',fullPage:true});});
test('switching panels and stale play promises cannot restart old playback',async({page})=>{await page.route('**/live-manga.json',async route=>{const response=await route.fetch(),m=await response.json();m.pages[0].panels[0].motion=m.pages[0].panels[1].motion;await route.fulfill({json:m});});await page.goto('/');const buttons=page.getByRole('button',{name:/再生/});await buttons.nth(0).click();await page.getByRole('button',{name:/再生/}).click();await expect(page.locator('video')).toHaveCount(1);await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime)).toBeGreaterThan(0);await page.getByRole('button',{name:/停止/}).click();await expect(page.locator('video')).toHaveCount(0);await page.getByRole('button',{name:/再生/}).first().focus();await page.keyboard.press('Enter');await expect(page.locator('video')).toHaveCount(1);await page.evaluate(()=>{Object.defineProperty(document,'hidden',{value:true,configurable:true});document.dispatchEvent(new Event('visibilitychange'));});await expect(page.locator('video')).toHaveCount(0);});

test('failed overlay selects the completed page and offscreen playback stops',async({page})=>{
 await page.setViewportSize({width:1100,height:500});
 await page.goto('/');const overlay=await page.locator('.overlay').getAttribute('src');await page.route('**'+overlay,r=>r.fulfill({status:404}));await page.reload();await expect(page.locator('.overlay')).toHaveCount(0);await expect(page.getByRole('button',{name:/再生/})).toHaveCount(0);await expect.poll(()=>page.locator('.page img').evaluate(im=>im.complete&&im.naturalWidth>0)).toBe(true);
 await page.unroute('**'+overlay);await page.reload();await page.getByRole('button',{name:/再生/}).click();await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));await expect(page.locator('video')).toHaveCount(0);
});
test('late play resolution is ignored after another panel starts',async({page})=>{
 await page.route('**/live-manga.json',async r=>{const res=await r.fetch(),m=await res.json();m.pages[0].panels[0].motion=m.pages[0].panels[1].motion;await r.fulfill({json:m});});await page.goto('/');await page.evaluate(()=>{const play=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){const p=play.call(this);return p.then(()=>new Promise(resolve=>{window.releasePlay=resolve;}));};});await page.getByRole('button',{name:/再生/}).first().click();await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime)).toBeGreaterThan(0);await page.evaluate(()=>{window.oldPlay=window.releasePlay;});await page.getByRole('button',{name:/再生/}).click();await page.evaluate(()=>window.oldPlay());await expect(page.locator('video')).toHaveCount(1);await expect.poll(()=>page.locator('video').evaluate(v=>v.currentTime)).toBeGreaterThan(0);
});
